version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/install-apache.sh
      timeout: 300
      runas: root
    - location: scripts/start-apache.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop-apache.sh
      timeout: 300
      runas: root